# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.86352445 0.06699193 0.94547261]
  [0.68528345 0.2488389  0.27755421]
  [0.11396259 0.17185472 0.8696359 ]]

 [[0.55006882 0.87152705 0.68728524]
  [0.54791625 0.62414074 0.738974  ]
  [0.28657814 0.34162488 0.94789818]]

 [[0.87232535 0.09219956 0.48736856]
  [0.42997054 0.19095737 0.28920137]
  [0.54729742 0.38694937 0.3723376 ]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
x = np.diag([1, 2, 3, 4,5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [4]:
x= np.random.random((3,3))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.67340483 0.37520508 0.21980536]
 [0.64884381 0.14422135 0.44610593]
 [0.27773861 0.43930191 0.37580969]]
After normalization:
[[1.         0.43649082 0.1428314 ]
 [0.95358695 0.         0.57047242]
 [0.25230807 0.55761484 0.43763335]]


# 5.  How to find common values between two arrays?

In [5]:
a1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",a1)
a2 = [10, 30, 40]
print("Array2: ",a2)
print("Common values between two arrays:")
print(np.intersect1d(a1, a2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [6]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-25
Today:  2020-07-26
Tomorrow:  2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [7]:
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[1 1 1 1 0 1]
Second array:
[0 0 0 1 0 0]
Test above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [8]:
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Original array:
[0.834281   0.99568144 0.64340507 0.9039351  0.78985244 0.1419852
 0.67311552 0.44455393 0.33571596 0.75196549]
Maximum value replaced by 0:
[0.834281   0.         0.64340507 0.9039351  0.78985244 0.1419852
 0.67311552 0.44455393 0.33571596 0.75196549]


# 9. How to print all the values of an array?

In [9]:
x = np.zeros((4, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [10]:
print("Original matrix:\n")
X = np.random.rand(2, 4)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.50196622 0.19587289 0.31161839 0.72728639]
 [0.12694643 0.79487556 0.44285123 0.3973137 ]]

Subtract the mean of each row of the said matrix:

[[ 0.06778025 -0.23831308 -0.12256758  0.29310042]
 [-0.3135503   0.35437883  0.0023545  -0.04318303]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [4]:
print("Original matrix:\n")
X = np.random.rand(2, 4)
print(X)
print("\nAdding 1 :\n")
Y = 1 + X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.59031502 0.287291   0.13885059 0.83310374]
 [0.29987398 0.06027005 0.69303942 0.31704891]]

Adding 1 :

[[1.46239009]
 [1.34255809]]


# 12.How to get the diagonal of a dot product?

# 13.How to find the most frequent value in an array?

In [11]:
x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[6 5 2 5 2 7 1 9 2 9 0 3 3 6 1 9 1 8 7 4 4 4 0 6 4 3 9 6 5 1 8 9 6 5 5 7 3
 9 2 7]
Most frequent value in the above array:
9


# 14.How to get the n largest values of an array

In [12]:
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


# 15.How to create a record array from a regular array?

In [13]:
arra1 = np.array([("aaa", 88.5, 90),
                 ("bbb", 87, 99),
             ("ccc", 85.5, 91)])
print("Original arrays:")
print(arra1)
print("\nRecord array;")
result = np.core.records.fromarrays(arra1.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
print(result)

Original arrays:
[['aaa' '88.5' '90']
 ['bbb' '87' '99']
 ['ccc' '85.5' '91']]

Record array;
[(b'aaa', 88.5, 90) (b'bbb', 87. , 99) (b'ccc', 85.5, 91)]
